services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ontoolaz-dev
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
      - .env:/app/.env
    restart: unless-stopped
