services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ontoolaz-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
