services:
  app:
    image: registry.gitlab.com/huongdev-2025/ontoolaz/frontend:master-${IMAGE_TAG}
    container_name: ontoolaz-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
