services:
  strapi:
    build: .
    container_name: strapi-app
    working_dir: /srv/app
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: development
    volumes:
      - .:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: strapi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: strapi-pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: ${DATABASE_USERNAME}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  mysql_data: